[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "IOTRACK"
authors = [{name = "Actia Telematics Services", email = "it@actia.be"}]
dynamic = ["version", "description"]
